// frameworks/react-basic/src/App.tsx
import { Route, Routes } from 'react-router'
import { routes } from './routes'
import { SideBar } from '@/components/SideBar'
import './App.scss'

function App() {  
  return (
    <div className="app-container">
      <SideBar routes={routes} />
      <section className="app-content">
        <Routes>
          {
            routes.map((route) => {
              const Component = route.Component!
              return (
                <Route path={route.path} element={<Component />} key={route.path} />
              )
            })
          }
        </Routes>
      </section>
    </div>
  )
}

export default App

// frameworks/vue-basic/src/App.vue
<script setup lang="ts">
import SideBar from '@/components/SideBar.vue';
</script>

<template>
  <main class="app-container">
    <SideBar />
    <section class="app-content">
      <router-view />
    </section>
  </main>
</template>

<style scoped lang="scss">
.app-container {
  display: flex;
  flex-direction: row;
  height: 100vh;
  .app-content {
    padding: 0 20px;
    flex: 1;
  }
}
</style>
